config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#index'

  namespace :admins do
    resources :rooms, only: %i[index show]
  end
  get 'rooms/enter', to: 'rooms#enter'

  mount ActionCable.server => '/cable'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :admin_rooms, dependent: :destroy
  has_many :rooms, through: :admin_rooms
  has_many :messages, as: :messageable

  # messageable interface
  def sender_name
    'サポート'
  end
end

app/models/admin_room.rb
class AdminRoom < ApplicationRecord
  belongs_to :admin
  belongs_to :room
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  attr_accessor :remember_token
  has_one :customer_room, dependent: :destroy
  has_one :room, through: :customer_room
  has_many :messages, as: :messageable

  # messageable interface
  def sender_name
    'ゲスト'
  end

  def registration
    self.remember_token = new_token
    update_attribute(:remember_digest, digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def new_token
    SecureRandom.urlsafe_base64
  end
end

app/models/customer_room.rb
class CustomerRoom < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }

  belongs_to :messageable, polymorphic: true
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_one :customer_room, dependent: :destroy
  has_one :customer, through: :customer_room
  has_many :admin_rooms, dependent: :destroy
  has_many :admins, through: :admin_rooms
  has_many :messages
end

app/controllers/admins/rooms_controller.rb
module Admins
  class RoomsController < ApplicationController
    before_action :authenticate_admin!

    def index
      @rooms = current_admin.rooms
    end

    def show
      @room = Room.find(params[:id])
      @messages = @room.messages
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include CustomerAuthenticator
  before_action :registered_confirmation

  def enter
    @current_customer = current_customer
    @room = @current_customer.room
    @messages = @room.messages

    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def registration
    customer = Customer.create
    customer.registration
    cookies.permanent.signed[:customer_id] = customer.id
    cookies.permanent[:remember_token] = customer.remember_token
    room = Room.create
    room.create_customer_room(customer: customer)
    room.admin_rooms.create(admin: Admin.first)
    @current_customer = customer
  end

  def current_customer
    if (customer_id = cookies.signed[:customer_id])
      customer ||= Customer.find_by(id: customer_id)
      if customer&.authenticated?(cookies[:remember_token])
        @current_customer = customer
      end
    end
  end

  def registered_confirmation
    registration unless current_customer
  end
end

app/views/admins/rooms/index.html.slim
h1 index

- @rooms.each do |room| 
  = link_to("#{room.id}", admins_room_path(room))

app/views/admins/rooms/show.html.slim
h1 show

h3 messages

#messages(data-room_id="#{@room.id}")
  = render(partial: "messages/message", collection: @messages)

form
  label Say something:<br>
  input(type="text" data-behavior="room_speaker")

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= @current_customer&.id %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div id="vue-root">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'vue_app' %>
  </body>
</html>

app/views/messages/_message.html.slim
p 
  = "#{message.messageable.sender_name}: #{message.content}"

app/views/rooms/_messages.html.slim
#vue-template-messages
  .chat
    .header(v-on:click='open')
      .title
        | message
      .close-btn(v-on:click='close')
        | x
    .content(v-show='isOpen')
      #messages(data-room_id="#{@room.id}")
        = render(partial: 'messages/message', collection: @messages)

      form
        textarea(type='text' data-behavior='room_speaker')

app/views/rooms/enter.html.slim
h1 Customer

h3 messages

#messages
  = render(partial: "messages/message", collection: @messages)

form
  label Say something:<br>
  input#room_id(value="#{@room.id}" type="hidden")
  input(type="text" data-behavior="room_speaker")

app/views/rooms/show.html.slim
h1 Customer

== render 'messages'

app/views/rooms/widget.html.slim
h1 widget

h3 messages

p
  = current_customer.id
p
  = @room.id

#messages
  = render(partial: "messages/message", collection: @messages)

form
  label Say something:<br>
  input#room_id(value="#{@room.id}" type="hidden")
  input(type="text" data-behavior="room_speaker")